# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/demystifyopenclaw',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/demystifyopenclaw',
                'lib_path': 'demystifyopenclaw'},
  'syms': {'demystifyopenclaw.core': {'demystifyopenclaw.core.foo': ('core.html#foo', 'demystifyopenclaw/core.py')}}}
