"""This section provides an overview of the baseline tasks for benchmarking nanobot capabilities."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_baseline.ipynb.

# %% auto #0
__all__ = ['SourceEnum', 'ToolCountClassEnum', 'CompositionDepthEnum', 'PlanningHorizonEnum', 'ScaffoldTypeEnum',
           'GoalConditionTypeEnum', 'KPIEnum', 'NANOBOT_TOOLS', 'GoalCondition', 'InterventionPolicy',
           'BaselineTaskSchema', 'save_baseline_tasks', 'load_baseline_tasks', 'fetch_gaia', 'filter_gaia_tasks',
           'map_gaia_tools', 'map_gaia_row']

# %% ../nbs/01_baseline.ipynb #62692784
from datasets import load_dataset
from pathlib import Path
from pydantic import BaseModel, Field
from typing import List, Literal, Any
import json

# %% ../nbs/01_baseline.ipynb #8321ba94
# Literal Definitions from Experimental Constraints 
SourceEnum = Literal["GAIA", "BFCL", "tau-bench"]
ToolCountClassEnum = Literal["single_tool", "multi_tool"]
CompositionDepthEnum = Literal["1", "2_3", "4_plus"]
PlanningHorizonEnum = Literal["short", "medium", "long"]
ScaffoldTypeEnum = Literal["memory", "prompt_scaffold", "multi_agent", "combined"]
GoalConditionTypeEnum = Literal[
    "text_match", 
    "file_creation", 
    "json_state_match", 
    "exit_code", 
    "answer_set_match"
]
KPIEnum = Literal[
    "Reasoning-First Success Rate",
    "Soft-Scaffolding Gain",
    "Fallback Justification Rate",
    "Task Completion Rate",
    "Tool Selection Accuracy",
    "Decomposition Stability",
    "Retry Count per Task",
    "Retry Improvement",
    "Context Degradation",
    "Hallucination Rate",
    "Autonomous Duration",
    "Plan Length vs Failure"
]

# Nested Pydantic Models
class GoalCondition(BaseModel):
    type: GoalConditionTypeEnum
    target: Any  # Can be a string, dict (for json_state), or int (for exit_code)
    match_mode: Literal["exact", "bounded", "includes"]

class InterventionPolicy(BaseModel):
    reasoning_first: bool = True
    soft_scaffold_allowed: List[ScaffoldTypeEnum] = Field(default_factory=list)
    hard_fallback_allowed: bool = False

# Main Baseline Task Schema 
class BaselineTaskSchema(BaseModel):
    """
    Schema for tasks defined in baseline.json
    """
    id: str
    source: SourceEnum
    source_split: str
    task_family: str
    difficulty: str
    prompt: str

    primary_kpi: List[KPIEnum]

    # Required task-shape metadata
    tool_count_class: ToolCountClassEnum
    composition_depth: CompositionDepthEnum
    planning_horizon: PlanningHorizonEnum
    cross_api_mashup: bool

    available_tools_label: List[str]

    goal_condition: GoalCondition
    
    # Preference for "automatic" over human judgment as per design principles
    judge_mode: Literal["automatic", "manual"] = "automatic"
    risk_tags: List[str]

    intervention_policy: InterventionPolicy

# %% ../nbs/01_baseline.ipynb #4ebb5452
NANOBOT_TOOLS = [
    "cron",
    "edit_file",
    "exec",
    "glob",
    "grep",
    "list_dir",
    "message",
    "read_file",
    "spawn",
    "web_fetch",
    "web_search",
    "write_file"
]

# %% ../nbs/01_baseline.ipynb #9d2f87b7
def save_baseline_tasks(baseline_tasks: List[BaselineTaskSchema], path: Path | str = "data/baseline_tasks.json"):
    path = Path(path)
    if not path.parent.exists():
        path.parent.mkdir(parents=True)
    with open(path, "w") as f:
        json.dump([task.model_dump() for task in baseline_tasks], f, indent=2)

def load_baseline_tasks(path: Path | str = "data/baseline_tasks.json") -> List[BaselineTaskSchema]:
    path = Path(path)
    with open(path, "r") as f:
        data = json.load(f)
    return [BaselineTaskSchema(**item) for item in data]

# %% ../nbs/01_baseline.ipynb #4d23ac4d
def fetch_gaia():
    print("Fetching GAIA data...")
    # Load the 2023 validation split
    dataset = load_dataset("gaia-benchmark/GAIA", "2023_all", split="validation")
    return dataset

# %% ../nbs/01_baseline.ipynb #20686257
def filter_gaia_tasks(
    tasks: list[dict],  # List of GAIA tasks
    levels: list[int] = [1, 2, 3],  # Difficulty levels to include
    included_tools: list[str] = None,  # Tools that must be included
    excluded_tools: list[str] = None,  # Tools that must not be included
    maximum_steps: int = None,  # Maximum number of steps in the solution
) -> list[dict]:
    """
    Filter GAIA tasks based on specified criteria.
    
    Args:
        tasks: List of GAIA task dictionaries.
        levels: List of difficulty levels to include (default: [1, 2, 3]).
        included_tools: List of tools that must be included in the solution (default: None).
        excluded_tools: List of tools that must not be included in the solution (default: None).
        maximum_steps: Maximum number of steps allowed in the solution (default: None).
    
    Returns:
        A list of filtered GAIA task dictionaries.
    """
    filtered = []
    for task in tasks:
        # Check difficulty level
        if int(task['Level']) not in levels:
            continue
        
        tools = task['Annotator Metadata']['Tools'] \
            if 'Annotator Metadata' in task and 'Tools' in task['Annotator Metadata'] else []
        
        # Check included tools
        if included_tools is not None:
            if not any(tool in tools.lower() for tool in included_tools):
                continue
        
        # Check excluded tools
        if excluded_tools is not None:
            if any(tool in tools.lower() for tool in excluded_tools):
                continue
        
        # Check maximum steps
        if maximum_steps is not None:
            if 'Annotator Metadata' in task and 'Number of steps' in task['Annotator Metadata']:
                if int(task['Annotator Metadata']['Number of steps']) > maximum_steps:
                    continue
        
        filtered.append(task)
    
    return filtered

# %% ../nbs/01_baseline.ipynb #6ad79535
def map_gaia_tools(
    tool_name: str,
):
    if not tool_name:
        return None
        
    t = tool_name.lower().strip('. ')
    if t in ["none", "no tools required"]:
        return None
    if t in NANOBOT_TOOLS:
        return t

    # 1. Web Navigation & Fetching (Direct URLs, Wikipedia, Archives)
    if any(keyword in t for keyword in ["browser", "archive", "wikipedia", "journal"]):
        return "web_fetch"

    # 2. Web Searching (Google, generic search engines)
    if "search" in t:
        return "web_search"

    # 3. Code Execution & Computation (Python, calculators, compiling, custom scripts)
    # Since your agent has 'exec', it can use bash/python to do math and text reversal natively.
    if any(keyword in t for keyword in [
        "python", "compiler", "script", "code", "algebra", 
        "calculator", "counter", "counting"
    ]):
        return "exec"

    # 4. File Handling & Editing (Text editors, markdown)
    if any(keyword in t for keyword in ["file handling", "editor", "markdown"]):
        return "edit_file"

    # 5. Text Processing (Diffs, NLP)
    if any(keyword in t for keyword in ["diff", "text processing", "natural language"]):
        return "grep"

    # Fallback: If something slips through, 'exec' is the safest bet for an LLM agent
    # because it allows the agent to figure it out using standard Linux/Python commands.
    return "exec"

# %% ../nbs/01_baseline.ipynb #98b33a23
def map_gaia_row(task: dict) -> BaselineTaskSchema:
    """Translates a raw GAIA row into the strict BaselineTaskSchema."""
    if "Annotator Metadata" not in task:
        print(f"Warning: Task {task.get('task_id', 'unknown')} is missing 'Annotator Metadata'. Defaulting to level 1 assumptions.")
        level = 1
    else:
        level = int(task["Annotator Metadata"].get("Level", 1))
    
    # 1. Level-based Heuristics for the Enums
    if level == 1:
        diff = "easy"
        depth = "1"
        horizon = "short"
        tool_class = "single_tool"
        mashup = False
    elif level == 2:
        diff = "medium"
        depth = "2_3"
        horizon = "medium"
        tool_class = "multi_tool"
        mashup = True
    else:  # Level 3
        diff = "hard"
        depth = "4_plus"
        horizon = "long"
        tool_class = "multi_tool"
        mashup = True

    # 2. Tool Mapping
    if "Annotator Metadata" in task and "Tools" in task["Annotator Metadata"]:
        raw_tools = task["Annotator Metadata"]["Tools"].lower().split("\n")
        tools = [re.sub(r'^\d+\.\s*', '', item) for item in raw_tools]
        mapped_tools = list(set(map_gaia_tools(tool) for tool in tools if map_gaia_tools(tool) is not None))
    else:
        mapped_tools = []

    # 3. Instantiate and Validate
    return BaselineTaskSchema(
        id=task.get("task_id", "unknown"),
        source="GAIA",
        source_split=f"level_{level}",
        
        # GAIA covers many domains, but for a default bucket:
        task_family="general_reasoning", 
        difficulty=diff,
        prompt=task.get("Question", ""),
        
        # Aligned with your KPI-to-benchmark mapping for GAIA
        primary_kpi=["Task Completion Rate", "Decomposition Stability"],
        
        tool_count_class=tool_class,
        composition_depth=depth,
        planning_horizon=horizon,
        cross_api_mashup=mashup,
        available_tools_label=mapped_tools,
        
        goal_condition={
            "type": "text_match",
            "target": str(task.get("Final answer", "")),
            "match_mode": "exact"
        },
        
        judge_mode="automatic",
        risk_tags=["multi_step", "context_fragility"] if level >= 2 else ["single_step"],
        
        intervention_policy={
            "reasoning_first": True,
            "soft_scaffold_allowed": ["prompt_scaffold", "memory", "combined"],
            "hard_fallback_allowed": False
        }
    )
