"""This section provides instructions on how to set up the project environment, including installation of necessary dependencies and configuration steps."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_setup.ipynb.

# %% auto #0
__all__ = ['LLM_PROVIDER', 'LLM_BASE_API', 'LLM_API_KEY', 'LLM_MODEL', 'LLM_MAX_TOKENS', 'LLM_CONTEXT_WINDOW', 'LLM_TEMPERATURE',
           'WEB_SEARCH_ENGINE', 'WEB_SEARCH_BASE_URL', 'WEB_SEARCH_API_KEY', 'WEB_SEARCH_MAX_RESULTS',
           'WEB_SEARCH_TIMEOUT', 'ENV_TASK_SET', 'ENV_LOG_FORMAT', 'DATA_DIR', 'DATA_LOG_DIR',
           'ENV_API_BUDGET_EXPECTED_USD', 'ENV_API_BUDGET_HARD_MAX_USD', 'verify_environment_variables',
           'adapt_nanobot_configuration']

# %% ../nbs/00_setup.ipynb #43345c25
import json
import os
from dotenv import load_dotenv
from pathlib import Path

# %% ../nbs/00_setup.ipynb #db21a477
# Load secrets from the .env file into the environment
load_dotenv()

# --- LLM Provider & Model Conditions ---
LLM_PROVIDER = "ollama"
LLM_BASE_API = "http://127.0.0.1:11434/v1"
LLM_API_KEY = os.getenv("LLM_API_KEY") 
LLM_MODEL = "ministral-3:8b" 
LLM_MAX_TOKENS = 8192
LLM_CONTEXT_WINDOW = 131072
LLM_TEMPERATURE = 0.1

# --- Web Search Engine Configuration ---
WEB_SEARCH_ENGINE = "tavily"
WEB_SEARCH_BASE_URL = "https://api.tavily.com/"
WEB_SEARCH_API_KEY = os.getenv("WEB_SEARCH_API_KEY")
WEB_SEARCH_MAX_RESULTS = 5
WEB_SEARCH_TIMEOUT = 30

# --- Environment & Data ---
ENV_TASK_SET = "tasks/baseline.json"
ENV_LOG_FORMAT = "json"

DATA_DIR = "data"
DATA_LOG_DIR = os.path.join(DATA_DIR, "logs")

# --- Budget Constraints ---
ENV_API_BUDGET_EXPECTED_USD = 30
ENV_API_BUDGET_HARD_MAX_USD = 50

# %% ../nbs/00_setup.ipynb #c5d65c5f
def verify_environment_variables():
    required_vars = [
        "LLM_API_KEY",
        "WEB_SEARCH_API_KEY"
    ]
    
    missing_vars = [var for var in required_vars if not os.getenv(var)]
    
    if missing_vars:
        raise EnvironmentError(f"Missing required environment variables: {', '.join(missing_vars)}")
    else:
        print("All required environment variables are set.")

# %% ../nbs/00_setup.ipynb #aca1958d
def adapt_nanobot_configuration(config_file_path: str = None):
    """
    Adapt the nanobot configuration based on the current environment variables and conditions.
    
    This function can be extended to modify a configuration file or return a configuration dictionary
    that can be used by the nanobot agent during execution.
    
    Args:
        config_file_path (str, optional): Path to a configuration file to modify. If None, take the default file path.
    
    Returns:
        dict: A configuration dictionary with the adapted settings.
    """
    if config_file_path is None:
        home_dir = Path.home()
        config_file_path = home_dir / ".nanobot" / "config.json"
        if not config_file_path.exists():
            raise FileNotFoundError(f"Configuration file not found at {config_file_path}")
        
    # Load existing configuration
    with open(config_file_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    # Update default agent configuration with current environment settings
    config["agents"]["defaults"]["model"] = LLM_MODEL
    config["agents"]["defaults"]["provider"] = LLM_PROVIDER
    config["agents"]["defaults"]["contextWindowTokens"] = LLM_CONTEXT_WINDOW
    config["agents"]["defaults"]["maxTokens"] = LLM_MAX_TOKENS
    config["agents"]["defaults"]["temperature"] = LLM_TEMPERATURE

    # Update provider configuration with API keys and base URLs
    config["providers"]["ollama"]["apiKey"] = LLM_API_KEY
    config["providers"]["ollama"]["baseUrl"] = LLM_BASE_API

    # Update web search configuration
    config["tools"]["web"]["search"]["provider"] = WEB_SEARCH_ENGINE
    config["tools"]["web"]["search"]["baseUrl"] = WEB_SEARCH_BASE_URL
    config["tools"]["web"]["search"]["apiKey"] = WEB_SEARCH_API_KEY
    config["tools"]["web"]["search"]["maxResults"] = WEB_SEARCH_MAX_RESULTS
    config["tools"]["web"]["search"]["timeout"] = WEB_SEARCH_TIMEOUT

    # Save the updated configuration back to the file
    with open(config_file_path, 'w') as f:
        json.dump(config, f, indent=4)
    print(f"Configuration adapted and saved to {config_file_path}")
